//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClientApp.DigitalSignatureServRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DigitalSignatureServRef.DigitalSignatureServiceSoap")]
    public interface DigitalSignatureServiceSoap {
        
        // CODEGEN: Generating message contract since element name password from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signiture", ReplyAction="*")]
        TestClientApp.DigitalSignatureServRef.SignitureResponse Signiture(TestClientApp.DigitalSignatureServRef.SignitureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signiture", ReplyAction="*")]
        System.Threading.Tasks.Task<TestClientApp.DigitalSignatureServRef.SignitureResponse> SignitureAsync(TestClientApp.DigitalSignatureServRef.SignitureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignitureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Signiture", Namespace="http://tempuri.org/", Order=0)]
        public TestClientApp.DigitalSignatureServRef.SignitureRequestBody Body;
        
        public SignitureRequest() {
        }
        
        public SignitureRequest(TestClientApp.DigitalSignatureServRef.SignitureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignitureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sourceText;
        
        public SignitureRequestBody() {
        }
        
        public SignitureRequestBody(string password, string sourceText) {
            this.password = password;
            this.sourceText = sourceText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignitureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignitureResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestClientApp.DigitalSignatureServRef.SignitureResponseBody Body;
        
        public SignitureResponse() {
        }
        
        public SignitureResponse(TestClientApp.DigitalSignatureServRef.SignitureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignitureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignitureResult;
        
        public SignitureResponseBody() {
        }
        
        public SignitureResponseBody(string SignitureResult) {
            this.SignitureResult = SignitureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DigitalSignatureServiceSoapChannel : TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DigitalSignatureServiceSoapClient : System.ServiceModel.ClientBase<TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap>, TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap {
        
        public DigitalSignatureServiceSoapClient() {
        }
        
        public DigitalSignatureServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DigitalSignatureServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalSignatureServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalSignatureServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClientApp.DigitalSignatureServRef.SignitureResponse TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap.Signiture(TestClientApp.DigitalSignatureServRef.SignitureRequest request) {
            return base.Channel.Signiture(request);
        }
        
        public string Signiture(string password, string sourceText) {
            TestClientApp.DigitalSignatureServRef.SignitureRequest inValue = new TestClientApp.DigitalSignatureServRef.SignitureRequest();
            inValue.Body = new TestClientApp.DigitalSignatureServRef.SignitureRequestBody();
            inValue.Body.password = password;
            inValue.Body.sourceText = sourceText;
            TestClientApp.DigitalSignatureServRef.SignitureResponse retVal = ((TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap)(this)).Signiture(inValue);
            return retVal.Body.SignitureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClientApp.DigitalSignatureServRef.SignitureResponse> TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap.SignitureAsync(TestClientApp.DigitalSignatureServRef.SignitureRequest request) {
            return base.Channel.SignitureAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClientApp.DigitalSignatureServRef.SignitureResponse> SignitureAsync(string password, string sourceText) {
            TestClientApp.DigitalSignatureServRef.SignitureRequest inValue = new TestClientApp.DigitalSignatureServRef.SignitureRequest();
            inValue.Body = new TestClientApp.DigitalSignatureServRef.SignitureRequestBody();
            inValue.Body.password = password;
            inValue.Body.sourceText = sourceText;
            return ((TestClientApp.DigitalSignatureServRef.DigitalSignatureServiceSoap)(this)).SignitureAsync(inValue);
        }
    }
}
